# Spring
spring:
  data:
    mongodb:
      uri: mongodb://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}?authSource=admin&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false&connectTimeoutMS=10000&socketTimeoutMS=10000
  kafka:
    bootstrap-servers: ${KAFKA_SERVER}
    listener:
      missing-topics-fatal: false
    consumer:
      group-id: dynamic_order_listener
      auto-offset-reset: earliest

# Authorization
security:
  authorization:
    header: ${AUTHORIZATION_KEY}
    expected-value: ${AUTHORIZATION_VALUE}

# logging
logging:
  config: classpath:logs/logback-spring.xml
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.mongodb.driver: DEBUG
    fassto.fms: DEBUG

fms:
  connectivity:
    api:
      url: ${CONNECTIVITY_URL}
  slack:
    api:
      url: ${SLACK_URL}
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000

server:
  port: 9000
  tomcat:
    connection-timeout: 90000

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    mongodb:
      enabled: true
    diskspace:
      enabled: true
